#!/usr/bin/env bash
pushd ~

if [[ ! -e ./dotfiles ]]; then
  echo "cloning dotfiles from github"
  git clone git@github.com:andywiens/dotfiles.git
fi

if [[ -e ~/.profile ]]; then
  # complain
  echo -e ".profile is already here! Do you want to proceed? (y/n):\n"
  if [[ "n" = `read` ]]; then
    exit
  fi
 
fi

if [[ -e ~/.bashrc ]]; then
  # complain
  echo -e ".bashrc is already here! Do you want to proceed? (y/n):\n"
  if [[ "n" = `read` ]]; then
    exit
  fi
fi

echo "removing old .profile & .bashrc"
rm ~/.profile
rm ~/.bashrc

echo "linking new files"
ln -s ~/dotfiles/profile ~/.profile
ln -s ~/dotfiles/bashrc ~/.bashrc

popd
